CONDA_ENV: "llamafactory_new"
LLAMA_FACTORY_ROOT: "/path/to/LLaMA-Factory/"
BASE_MODEL_ROOT: "/path/to/base-model/"
TRAIN_META_INFO_ROOT: "./train_meta_info"
LORA_OUTPUT_ROOT: "/path/to/lora-output/"
