CONDA_ENV: "llamafactory_new"
LLAMA_FACTORY_ROOT: "/home/maning/git/LLaMA-Factory_20251215/LlamaFactory/"
BASE_MODEL_ROOT: "/data/opt/LLM_Base_Model/Qwen2.5-0.5B-Instruct/"
TRAIN_META_INFO_ROOT: "/data/exp_maning/optimization_API/train_meta_info"
LORA_OUTPUT_ROOT: "/data/opt/LLM_lora_SFT/saves/DPO_LORA/"
